#! /usr/bin/perl -w
# @code.pl
# Copyright(C)2014 chenxiang
#
#

my  $copytext="/".("*"x50)."\n* \@%s\n* CfgLib-xml\n* Copyright(C)2014 Hiang Chen\n* This file is autogenerated by perl script(./genhdr.pl)\n*/\n\n";
my  $filename="xml.h";

sub check_exist {
  if(-e "$filename"){
    printf  "Remove Original File (%s).\n",$filename;
  }
  open  FLE ,">$filename";
  printf  FLE $copytext,$filename;
  close FLE;
}

sub list_functions {
  my  $aline;
  my  $define;
  open  LST,">>$filename";
  $define="_".$filename."_XML"."_";
  $define=~s/\./_/;
  $define=~s/(\w+)/\U$1/g;
  printf  LST "#ifndef\t%s\n#define\t%s\n",$define,$define;
  printf  LST "#ifdef\t__cplusplus\n";
  printf  LST "extern \"C\" {\n#endif\n\n";
  printf  "xml.c\n";
  open  SRC,"<xml.c";
  while(defined($aline=<SRC>)){
    chomp($aline);
    if($aline=~m/^int(\s+|\t+)[a-z]\w+/){
      printf  LST "%s;\n",$aline;
    }
    if($aline=~m/^void[*](\s+|\t+)[a-z]\w+/){
      printf  LST "%s;\n",$aline;
    }
    if($aline=~m/^const(\s+|\t+)char[*]/){
      printf  LST "%s;\n",$aline;
    }
  }
  close SRC;
  printf  LST "\n#ifdef\t__cplusplus\n";
  printf  LST "}\n#endif\n";
  printf  LST "#endif\n";
  close LST;
}

&check_exist;
&list_functions;
