/**************************************************
* @xml.h
* CfgLib-xml
* Copyright(C)2014 Hiang Chen
* This file is autogenerated by perl script(./genhdr.pl)
*/

#ifndef	_XML_H_XML_
#define	_XML_H_XML_
#ifdef	__cplusplus
extern "C" {
#endif

const char* xml_version();
void* xml_init_document(const char* filename);
int xml_free_document(void* handle);
int xml_get_element_text(void* handle,const char* path,const char* buf,int cb,int mode);
int xml_set_element_text(void* handle,const char* path,const char* buf,int mode);
int xml_get_element_attributes(void* handle,const char* path,const char* name,const char* buf,int cb,int mode);
int xml_set_element_attributes(void* handle,const char* path,const char* name,const char* buf,int mode);
int xml_update_document(void* handle);
int xml_write_document(void* handle,const char* filename);
void* xml_node_branch_open(void* handle,const char* path);
void* xml_node_branch_go_next(void* treenode);
void* xml_node_branch_go_previous(void* treenode);
void* xml_node_branch_go_child(void* treenode);
void* xml_node_branch_insert(void* treenode,const char* tag,const char* attributes,int single,const char* text,const char* comment);
void* xml_node_branch_insert_child(void* treenode,const char* tag,const char* attributes,int single,const char* text,const char* comment);
int xml_node_branch_remove(void* treenode);

#ifdef	__cplusplus
}
#endif
#endif
